name: main-pr-generate

on:
  pull_request:
    types: [closed]
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  main-pr:
    if: startsWith(github.event.pull_request.title, 'chore(develop)')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Get Data
        id: get-data
        run: |
          git fetch origin develop

          # Get the latest commit message from develop and save to file
          git show origin/develop -s --format=%B | base64 > commit_msg.b64
  
          # Also extract the version string from the message
          VERSION=$(git show origin/develop -s --format=%B | grep -oP '\d+\.\d+\.\d+' || true)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"


      - name: Create PR from develop to main
        id: create-pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_URL=$(gh pr create \
          --base main \
          --head develop \
          --title "$(echo "${{ github.event.pull_request.title }}" | sed 's/chore(develop):/chore(main):/')" \
          --body "${{ github.event.pull_request.body }}")

          PR_NUMBER=$(echo "$PR_URL" | grep -oE '[0-9]+$')
          echo "pull-request-number=$PR_NUMBER" >> "$GITHUB_OUTPUT"

      - name: Merge PR
        id: merge-pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git fetch origin main
            git checkout main

            # Extract and sanitize commit message
            MESSAGE=$(git show origin/develop -s --format=%B)

            # Replace 'chore(develop)' with 'chore(main)' only on the first line
            TITLE=$(echo "$MESSAGE" | head -n1 | sed 's/chore(develop):/chore(main):/')
            BODY=$(echo "$MESSAGE" | tail -n +2)

            # Reconstruct commit message
            echo -e "$TITLE\n\n$BODY" > merge_message.txt

            git merge --no-ff origin/develop -F merge_message.txt
            git push origin main


      - name: Add published label to PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: ${{ steps.create-pr.outputs.pull-request-number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["autorelease: published"]
            })

      - name: Tag main
        id: tag-main
        run: |
              git fetch origin main
              git tag -f "${{ steps.get-data.outputs.version }}"
              git push -f origin "${{ steps.get-data.outputs.version }}"
